### ISSUE TITLE
YOLOX无法训练

### ISSUE THREAD

**Issue by ZZY-666** [xialuxi/yolov5_all#5]
前辈您好  训练YOLOX的时候报错 请问您遇到过吗？
我是北矿的研究生 您方便留联系方式交流吗？感谢。
![image](https://user-images.githubusercontent.com/59229974/147387241-a5e0d591-cb71-4cb0-a242-b375b5e34f13.png)

**Comment by ZZY-666** [comment]
我会提供在v5中实现其他模块 如swin transformer  scse 等等 以便于更好的交流。
微信：zzy20011998

**Comment by starsky68** [comment]
> 前辈您好 训练YOLOX的时候报错 请问您遇到过吗？ 我是北矿的研究生 您方便留联系方式交流吗？感谢。 ![image](https://user-images.githubusercontent.com/59229974/147387241-a5e0d591-cb71-4cb0-a242-b375b5e34f13.png)

请问你这个怎么解决的
